
//----------------------------------------------------
// The following code was generated by CUP v0.10k TUM Edition 20050516
// Sat May 17 21:03:02 IDT 2008
//----------------------------------------------------

package IC.Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 43;
  public static final int LCBR = 27;
  public static final int LTE = 34;
  public static final int UMINUS = 49;
  public static final int INTEGER = 39;
  public static final int SEMI = 7;
  public static final int CONTINUE = 19;
  public static final int INT = 38;
  public static final int MINUS = 40;
  public static final int STATIC = 8;
  public static final int LT = 33;
  public static final int LP = 25;
  public static final int COMMA = 29;
  public static final int CLASS = 44;
  public static final int RP = 26;
  public static final int PLUS = 42;
  public static final int MULTIPLY = 41;
  public static final int ASSIGN = 46;
  public static final int QUOTE = 10;
  public static final int IF = 22;
  public static final int THIS = 11;
  public static final int DOT = 20;
  public static final int ID = 24;
  public static final int BOOLEAN = 47;
  public static final int EOF = 0;
  public static final int RCBR = 28;
  public static final int LB = 30;
  public static final int LAND = 16;
  public static final int RETURN = 6;
  public static final int EQUAL = 13;
  public static final int TRUE = 37;
  public static final int NEW = 3;
  public static final int error = 1;
  public static final int RB = 31;
  public static final int LOR = 15;
  public static final int NULL = 5;
  public static final int MOD = 4;
  public static final int BREAK = 48;
  public static final int VOID = 12;
  public static final int GTE = 35;
  public static final int ELSE = 23;
  public static final int WHILE = 18;
  public static final int NEQUAL = 14;
  public static final int CLASS_ID = 45;
  public static final int EXTENDS = 21;
  public static final int STRING = 9;
  public static final int LNEG = 17;
  public static final int FALSE = 36;
  public static final int GT = 32;
  public static final int LENGTH = 2;
}

